services:
  mongodb:
    image: mongo
    container_name: mongodb_mern
    networks:
      - mern-network
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: server
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=process.env.MONGO_URI
    networks:
      - mern-network

  client:
    build: ./client
    container_name: client
    ports:
      - "3001:3001"
    depends_on:
      - server
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
